package in.co.rays.Exception;

public class TestException {
	
	public static void main(String[] args) {
		
		try {
			
			int a=123;
			int b=0;
			int c=a/b;
			
		}catch (Exception e) {
			
			//System.out.println(e);
			//System.out.println(e.getMessage());
			e.printStackTrace();
			
		}
		
		
	}

}
